Debug healthcheck
Signed-off-by: Peter Nied <peternied@hotmail.com>

diff --git a/.github/workflows/sonar-qube.yml b/.github/workflows/sonar-qube.yml
--- a/.github/workflows/sonar-qube.yml
+++ b/.github/workflows/sonar-qube.yml
@@ -14,11 +14,11 @@ jobs:
         image: sonarqube:community
         ports:
           - 9000:9000
-        options: >-
-          --health-cmd="curl -s -u admin:admin http://localhost:9000/api/system/health | grep -o UP"
-          --health-interval=10s
-          --health-timeout=10s
-          --health-retries=60
+        # options: >-
+        #   --health-cmd="curl -s -u admin:admin http://localhost:9000/api/system/health | grep -o UP"
+        #   --health-interval=10s
+        #   --health-timeout=10s
+        #   --health-retries=60
         env:
           SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
 
@@ -30,8 +30,9 @@ jobs:
         distribution: 'temurin'
     - name: Wait for SonarQube to be ready
       run: |
-        until curl -s http://localhost:9000/api/system/health | grep -o UP; do
+        until curl -s -u admin:admin http://localhost:9000/api/system/health | grep -o UP; do
           echo "Waiting for SonarQube to be ready..."
+          curl -v -u admin:admin http://localhost:9000/api/system/health || true
           sleep 2
         done
         echo "SonarQube is ready."
